#docker-compose.yaml
version: "3.7"

services:
  go-todo:
    container_name: go_todo
    image: horlabyc/go-todo:dev
    build:
      context: .
      target: dev
    volumes:
      - .:/app
    ports:
      - "5000:5000"
      - "2345:2345"
    networks:
      - go-todo-network
  go-todo-db:
    container_name: go-todo-db
    image: postgres
    user: postgres
    environment: 
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - go-todo-network

volumes:
  postgres-db:
    
networks:
  go-todo-network:
    name: go-todo-network